name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create local.properties
        run: echo "${{ secrets.LOCAL_PROPERTIES }}" > local.properties
        shell: bash

      - name: Build Android app
        run: ./gradlew :android-app:testDebugUnitTest :android-app:assembleDebug

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: android-build-outputs
          path: android-app/build/outputs

  build-desktop:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create local.properties
        run: echo "${{ secrets.LOCAL_PROPERTIES }}" > local.properties
        shell: bash

      - name: Build Desktop app
        run: ./gradlew :desktop-app:packageDistributionForCurrentOS

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: desktop-app-build-${{ matrix.os }}
          path: desktop-app/build/compose/binaries/main/**/*

  build-ios:
    runs-on: macOS-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

      - name: Build iOS app
        run: cd iosApp && xcodebuild -target "iosApp" -configuration Debug -scheme iosApp -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16' CODE_SIGNING_ALLOWED='NO'
